elevator: elevator.c A3.c person.c sem.c
	gcc -g -Wall -c elevator.c
	gcc -g -Wall -c person.c
	gcc -g -Wall -c sem.c
	gcc -g -Wall -c A3.c
	gcc -g -Wall -o A3.out A3.o -lpthread elevator.o sem.c person.c
